name: python-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - python-multipart
  - pydub
  - ffmpeg
  - pip
  - pip:
      - openai-whisper
      - pyannote.audio
      - torch
      - torchvision
      - torchaudio
      - librosa
      - soundfile
      - ipywidgets
      - py-cpuinfo
      - psutil
      - dotenv
      - transformers            # for huggingface transformers
      - sentence-transformers   # for huggingface sentence-transformers
      - hf_xet                  # for huggingface xet (better download speed)
      - pymupdf                 # (imported as fitz): extracts text from PDF files.
      - ebooklib                # fparses EPUB files and extracts HTML content.
      - beautifulsoup4          # processes and cleans up HTML inside EPUBs.
      - html2text               # converts HTML to Markdown.
      - nltk                    # for text processing and tokenization.
      - langchain               # for chaining together LLMs and other components.
      - openai                  # for OpenAI API access.